management:
  zipkin:
    tracing:
      endpoint: http://zipkin-microservice:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

spring:
  kafka:
    bootstrap-servers: kafka:9092