spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:mhmmdnaufall.notificationservice.OrderPlacedEvent

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:

  # Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0

server:
  port: 0
